version: '3.8'

services:
  dbdumper:
    image: nilsmarti/go-dbdumper:latest
    environment:
      # Database configuration
      - DB_TYPE=mysql # or postgres
      - DB_HOST=db
      - DB_PORT=3306 # or 5432 for postgres
      - DB_NAME=mydb
      - DB_USER=dbuser
      - DB_PASSWORD=dbpassword
      
      # S3 configuration
      - S3_ENDPOINT=minio:9000
      - S3_REGION=us-east-1
      - S3_BUCKET=backups
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_USE_SSL=false
      
      # Backup configuration
      - CRON_EXPRESSION=0 0 * * * # Daily at midnight
      - KEEP_LAST=5 # Keep last 5 backups
      - BACKUP_PREFIX=myapp
    restart: unless-stopped
    depends_on:
      - minio

  # Example MinIO service for S3-compatible storage
  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    volumes:
      - minio_data:/data

  # Example MySQL service (uncomment to use)
  # db:
  #   image: mysql:8.0
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=rootpassword
  #     - MYSQL_DATABASE=mydb
  #     - MYSQL_USER=dbuser
  #     - MYSQL_PASSWORD=dbpassword
  #   volumes:
  #     - mysql_data:/var/lib/mysql

  # Example PostgreSQL service (uncomment to use)
  # db:
  #   image: postgres:14
  #   environment:
  #     - POSTGRES_DB=mydb
  #     - POSTGRES_USER=dbuser
  #     - POSTGRES_PASSWORD=dbpassword
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  minio_data:
  # mysql_data:
  # postgres_data:
